# Generated by Django 2.1.3 on 2018-11-09 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('delete', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=30)),
                ('contact', models.IntegerField(max_length=11)),
                ('gender', models.CharField(max_length=5)),
                ('created_date', models.DateField()),
                ('delete', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Registration'),
        ),
    ]
