# Generated by Django 2.1.3 on 2018-11-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='delete',
            field=models.IntegerField(verbose_name=5),
        ),
        migrations.AlterField(
            model_name='registration',
            name='delete',
            field=models.IntegerField(verbose_name=5),
        ),
    ]
