# Generated by Django 2.1.3 on 2018-11-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20181109_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='contact',
            field=models.IntegerField(verbose_name=11),
        ),
    ]
