# Generated by Django 2.1.3 on 2018-11-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20181109_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='created_date',
            field=models.DateField(blank=True),
        ),
    ]
