# Generated by Django 2.1.3 on 2018-12-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20181130_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='delete',
            field=models.IntegerField(blank=True, verbose_name=5),
        ),
    ]
