# Generated by Django 2.1.3 on 2018-12-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20181202_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='created_date',
        ),
    ]
