# Generated by Django 2.1.3 on 2018-12-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_registration_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='delete',
        ),
    ]
